[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "bin/rails server -p ${PORT:-3000} -e ${RACK_ENV:-development}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
